
# Where in Chicago Should I Live? An Independent Case Study
For my independent case study, I chose to analyze different neighborhoods in Chicago to make an data-driven, informed decision for when I start looking for apartments. Growing up in the Chicago suburbs, I have a general idea of different neighborhoods but not enough to make a decision on where I want to sign a lease next year. The purpose of this case study is to help me better understand Chicago's neighborhoods so I can make an informed decision on where to live. 
# Data Selection
The dataset I'm using is from the Chicago Metropolitan Agency for Planning. It has demographic information for 77 areas in Chicago.

In [1]:
import pandas as pd
import numpy as np
import plotly
import plotly.express as px
import plotly.graph_objects as go

Import Dataset

In [2]:
df = pd.read_csv('https://github.com/erinrt17/Chicago-Neighborhood-Independent-Case-Study/raw/main/ReferenceCCAProfiles20142018.csv')

In [3]:
df.shape

(77, 221)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Columns: 221 entries, GEOG to T_Cost_Mod
dtypes: float64(171), int64(29), object(21)
memory usage: 133.1+ KB

This dataset does not have any date time characterics

In [5]:
num_rows = df.shape[0]
num_cols = df.shape[1]

print(f'There are {num_rows} rows and {num_cols} columns in the dataset.')

There are 77 rows and 221 columns in the dataset.

In [6]:
df.head()

             GEOG  2000_POP  2010_POP  ...  H_Cost_Mod  T_Cost_Typical  T_Cost_Mod
0     Albany Park     57655     51542  ...         NaN             NaN         NaN
1  Archer Heights     12644     13393  ...         NaN             NaN         NaN
2   Armour Square     12032     13391  ...         NaN             NaN         NaN
3         Ashburn     39584     41081  ...         NaN             NaN         NaN
4  Auburn Gresham     55928     48743  ...         NaN             NaN         NaN

[5 rows x 221 columns]

In [7]:
df.tail()

            GEOG  2000_POP  2010_POP  ...  H_Cost_Mod  T_Cost_Typical  T_Cost_Mod
72     West Lawn     29235     33355  ...         NaN             NaN         NaN
73  West Pullman     36649     29651  ...         NaN             NaN         NaN
74    West Ridge     73199     71942  ...         NaN             NaN         NaN
75     West Town     87435     82236  ...         NaN             NaN         NaN
76      Woodlawn     27086     23740  ...         NaN             NaN         NaN

[5 rows x 221 columns]

In [8]:
df.sample(8)

            GEOG  2000_POP  2010_POP  ...  H_Cost_Mod  T_Cost_Typical  T_Cost_Mod
25   Fuller Park      3420      2876  ...         NaN             NaN         NaN
20     East Side     23653     23042  ...         NaN             NaN         NaN
36       Kenwood     18363     17841  ...         NaN             NaN         NaN
54       Oakland      6110      5918  ...         NaN             NaN         NaN
38  Lincoln Park     64320     64116  ...         NaN             NaN         NaN
75     West Town     87435     82236  ...         NaN             NaN         NaN
60      Roseland     52723     44619  ...         NaN             NaN         NaN
9        Beverly     21992     20034  ...         NaN             NaN         NaN

[8 rows x 221 columns]

Check which columns are empty

In [9]:
df.isnull()

     GEOG  2000_POP  2010_POP  ...  H_Cost_Mod  T_Cost_Typical  T_Cost_Mod
0   False     False     False  ...        True            True        True
1   False     False     False  ...        True            True        True
2   False     False     False  ...        True            True        True
3   False     False     False  ...        True            True        True
4   False     False     False  ...        True            True        True
..    ...       ...       ...  ...         ...             ...         ...
72  False     False     False  ...        True            True        True
73  False     False     False  ...        True            True        True
74  False     False     False  ...        True            True        True
75  False     False     False  ...        True            True        True
76  False     False     False  ...        True            True        True

[77 rows x 221 columns]

Drop empty columns

In [10]:
for column in df:
  if df[column].isnull().sum() >5:
    print('{0} has {1} null values'.format(column, df[column].isnull().sum()))
    df.drop(column, axis=1, inplace=True)

IDES_START_EMP has 76 null values
IDES_MID_EMP has 76 null values
IDES_CURR_EMP has 76 null values
RET_SALES has 77 null values
GEN_MERCH has 77 null values
RES_EAV has 77 null values
CMRCL_EAV has 77 null values
IND_EAV has 77 null values
RAIL_EAV has 77 null values
FARM_EAV has 77 null values
MIN_EAV has 77 null values
TOT_EAV has 77 null values
WALKSCORE has 77 null values
AG has 72 null values
Agperc has 72 null values
2000_UND19 has 76 null values
2000_A20_34 has 76 null values
2000_A35_49 has 76 null values
2000_A50_64 has 76 null values
2000_OV65 has 76 null values
2000_MED_AGE has 76 null values
2000_TOT_HH has 76 null values
2000_OWN_OCC_HU has 76 null values
2000_RENT_OCC_HU has 76 null values
2000_VAC_HU has 76 null values
2000_HU_TOT has 76 null values
2000_LT_HS has 76 null values
2000_HS has 76 null values
2000_SOME_COLL has 76 null values
2000_ASSOC has 76 null values
2000_BACH has 76 null values
2000_GRAD_PROF has 76 null values
2000_POP_25OV has 76 null values
HT_Cost_Typical has 76 null values
HT_Cost_Mod has 76 null values
H_Cost_Typical has 76 null values
H_Cost_Mod has 76 null values
T_Cost_Typical has 76 null values
T_Cost_Mod has 76 null values

Check dataset to make sure that empty columns were dropped

In [11]:
df.shape

(77, 182)

Sort dataset by my age group

In [12]:
df.sort_values('A20_34', ascending=False)

               GEOG  2000_POP  2010_POP  ...  2000_BLACK  2000_ASIAN  2000_OTHER
37        Lake View     94817     94368  ...        4193        5143        1850
75        West Town     87435     82236  ...        7979        1510        2535
46  Near North Side     72811     80484  ...       13884        4434        1291
38     Lincoln Park     64320     64116  ...        3323        2325        1077
40     Logan Square     82715     72791  ...        4290        1087        1763
..              ...       ...       ...  ...         ...         ...         ...
57          Pullman      8921      7325  ...        7262          15          92
6       Avalon Park     11147     10185  ...       10816          19         131
54          Oakland      6110      5918  ...        5957           8          47
12         Burnside      3294      2916  ...        3180           7          33
25      Fuller Park      3420      2876  ...        3225           6          55

[77 rows x 182 columns]

Sort data by median income

In [13]:
df.sort_values('MEDINC', ascending=False)

                  GEOG  2000_POP  2010_POP  ...  2000_BLACK  2000_ASIAN  2000_OTHER
50        North Center     31895     31867  ...        1333        1324         804
24         Forest Glen     18165     18508  ...          71        1586         326
38        Lincoln Park     64320     64116  ...        3323        2325        1077
65            The Loop     16388     29283  ...        3221        1625         398
22         Edison Park     11328     11187  ...          19         200          74
..                 ...       ...       ...  ...         ...         ...         ...
71  West Garfield Park     23019     18001  ...       22564          18         103
25         Fuller Park      3420      2876  ...        3225           6          55
19  East Garfield Park     20881     20567  ...       20296          25         118
23           Englewood     40222     30654  ...       39352          27         318
58           Riverdale      9809      6482  ...        9479           7          97

[77 rows x 182 columns]

Sort data by my salary range

In [14]:
df.sort_values('INC_50_75K', ascending=False)

               GEOG  2000_POP  2010_POP  ...  2000_BLACK  2000_ASIAN  2000_OTHER
37        Lake View     94817     94368  ...        4193        5143        1850
46  Near North Side     72811     80484  ...       13884        4434        1291
75        West Town     87435     82236  ...        7979        1510        2535
21        Edgewater     62198     56521  ...       10564        7172        2504
40     Logan Square     82715     72791  ...        4290        1087        1763
..              ...       ...       ...  ...         ...         ...         ...
57          Pullman      8921      7325  ...        7262          15          92
54          Oakland      6110      5918  ...        5957           8          47
25      Fuller Park      3420      2876  ...        3225           6          55
58        Riverdale      9809      6482  ...        9479           7          97
12         Burnside      3294      2916  ...        3180           7          33

[77 rows x 182 columns]

Group by residents' employment type to determine which is assocaited with the highest median income

In [15]:
df_employment = df.groupby('RES_NAICS1_TYPE', as_index=False)
df_employment.agg({'MEDINC': 'mean'})

                  RES_NAICS1_TYPE        MEDINC
0  Accommodation and Food Service  43764.534488
1                       Education  66346.170560
2                     Health Care  42568.291417
3                   Manufacturing  45039.597744
4                    Professional  87975.321214
5           Public Administration  99817.757750

Determine Chicago's distribution of neighborhoods with a bachelor's degree or higher education

In [16]:
fig = px.box(df, y='BACH', title='Bachelor Degree Distribution')
fig.show()

Determine which neighborhoods have access to open space

In [17]:
fig = px.density_heatmap(df,x='OPEN_SPACE_PER_1000', y='GEOG', title='Two Bedroom Apartments with Access to Open Space')
fig.show()

Distrubtion of Median Income by my Age Group

In [18]:
fig = px.scatter(df, x='A20_34', y='MEDINC', title='Median Income by my Age Group')
fig.show()

Areas with population in my age group and salary range

In [19]:
fig = px.scatter_3d(df, x='A20_34', y='INC_50_75K', z='GEOG', title='Areas with my age and salary range with two bedroom apartments')
fig.show()

Pie chart of neighborhoods with population in my age group

In [20]:
fig=px.pie(df, values='A20_34', names='GEOG', title='My age group by neighborhood')
fig.show()

After analyzing the data in python, I have a relative basis for neighborhoods that I would like to live in. I would like to be in place with other people my age, making a similar amount of money and have a similar degree of education. Based on this analysis, the young neighborhoods are Lake View, West Town and the Near North Side. I think I'll be priced out of the North Center, Forest Glen and Lincoln Park but I could reasonably afford to live in Lake View, Near North Side or West Town.